# Generated by Django 3.2.5 on 2021-12-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
    ]
